#!/bin/bash

sudo yum -y install epel-release
sudo yum -y install rpm-build gcc gcc-c++ libstdc++-devel binutils-devel
sudo yum -y install m4 cmake qt qt-devel qtwebkit qtwebkit-devel flex

mkdir $1
cd $1
installFolder=`pwd`
echo "alias fe31='source $installFolder/foam-extend-3.1/etc/bashrc'" >> ~/.bashrc 

git clone https://github.com/Unofficial-Extend-Project-Mirror/\
openfoam-extend-foam-extend-3.1.git
mv openfoam-extend-foam-extend-3.1 foam-extend-3.1

echo "export QT_BIN_DIR=/usr/lib64/qt4/bin" >> ~/.bash_profile
. ~/.bash_profile
. ~/.bashrc
fe31
cd $FOAM_SRC
wmakeLnIncludeAll

cd ../ThirdParty/

## revising spec files needed
sed -i "/PyFoam-0.6.3.tar.gz/c    ( rpm_make -p PyFoam-0.6.3 -s PyFoam-0.6.3.spec  -u  http://openfoamwiki.net/images/c/cb/PyFoam-0.6.3.tar.gz -n PyFoam-0.6.3-1.noarch -a noarch )" AllMake.stage3
sed -i "/PyFoam-0.6.3-rc.tar.gz/c URL:                    http://openfoamwiki.net/images/e/e3/PyFoam-0.6.3-rc.tar.gz" rpmBuild/SPECS/PyFoam-0.6.3.spec
sed -i "s/-rc//g" rpmBuild/SPECS/PyFoam-0.6.3.spec

./AllMake > log.make3rdParty 2>&1 

cd ../
./Allwmake > log.make 2>&1 
